/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-1` | `/dummy/tab-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-2` | `/dummy/tab-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-3` | `/dummy/tab-3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-4` | `/dummy/tab-4`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/settings/roles` | `/settings/roles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/settings/tasks` | `/settings/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/settings/users` | `/settings/users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/public/about` | `/public/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(unauthenticated)'}/login` | `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-1` | `/dummy/tab-1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-2` | `/dummy/tab-2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-3` | `/dummy/tab-3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-4` | `/dummy/tab-4`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/settings/roles` | `/settings/roles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/settings/tasks` | `/settings/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authenticated)'}/settings/users` | `/settings/users`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/public/about` | `/public/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(unauthenticated)'}/login` | `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/dummy/tab-1${`?${string}` | `#${string}` | ''}` | `/dummy/tab-1${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/dummy/tab-2${`?${string}` | `#${string}` | ''}` | `/dummy/tab-2${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/dummy/tab-3${`?${string}` | `#${string}` | ''}` | `/dummy/tab-3${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/dummy/tab-4${`?${string}` | `#${string}` | ''}` | `/dummy/tab-4${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/settings/roles${`?${string}` | `#${string}` | ''}` | `/settings/roles${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/settings/tasks${`?${string}` | `#${string}` | ''}` | `/settings/tasks${`?${string}` | `#${string}` | ''}` | `${'/(authenticated)'}/settings/users${`?${string}` | `#${string}` | ''}` | `/settings/users${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/public/about${`?${string}` | `#${string}` | ''}` | `/public/about${`?${string}` | `#${string}` | ''}` | `${'/(unauthenticated)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-1` | `/dummy/tab-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-2` | `/dummy/tab-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-3` | `/dummy/tab-3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/dummy/tab-4` | `/dummy/tab-4`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/settings/roles` | `/settings/roles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/settings/tasks` | `/settings/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authenticated)'}/settings/users` | `/settings/users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/public/about` | `/public/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(unauthenticated)'}/login` | `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
