export { CRUDList } from './CRUDList'
export { CRUDDetail } from './CRUDDetail'
export { CRUDCreate } from './CRUDCreate'
export { CRUDUpdate } from './CRUDUpdate'
export { CRUDRouteHeader } from './CRUDRouteHeader'
